### ISSUE TITLE
Missing Microsoft.VisualStudio.Threading

### ISSUE THREAD

**Issue by rani-pinchuk** [Benio101/Color.Comment#2]
# Bug report

Hi Paweł and thanks for writing this promising extension!

### Short Description

See https://github.com/Benio101/Color.Token/issues/3 
It is practically the same bug but for the Color.Comment

### Steps to reproduce

1. Install Color.Comment on Microsoft Visual Studio 2017 version: 15.0.28307.489
2. Start Visual Studio 2017. 

#### Expected behavior

It works.

#### Actual behavior

An error. 
In the ActivityLog.xml you get `SetSite failed for package [Package]Source: &apos;Color.Comment&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=16.0.0.0, `

## Additional informations

As said, see https://github.com/Benio101/Color.Token/issues/3

Thanks, 

Rani

**Comment by Benio101** [comment]
Description of this issue sounds exactly same as #1. I've applied a fix to that in 8454dd74b6ca88e101337a5748a0d85615f8508d.
> Fixed in [`0.0.2+2017`](https://github.com/Benio101/Color.Comment/releases/tag/0.0.2%2B2017). Live on marketplace.

Right now, [`2017`](https://github.com/Benio101/Color.Comment/tree/2017) branch of `Color.Comment` references `Microsoft.VisualStudio.Threading` in version [`15.8.209`](https://github.com/Benio101/Color.Comment/blob/8454dd74b6ca88e101337a5748a0d85615f8508d/Color.Comment/Color.Comment.csproj#L114) once [`fix: downgrade nugets back from 16 to 15`](https://github.com/Benio101/Color.Comment/commit/8454dd74b6ca88e101337a5748a0d85615f8508d) commit was applied.

On marketplace, there is a [`0.0.2+2017`](https://github.com/Benio101/Color.Comment/releases/tag/0.0.2%2B2017) version (visible as `0.0.2` on marketplace), which comes from the [`2017`](https://github.com/Benio101/Color.Comment/tree/2017) branch, which build [passed](https://ci.appveyor.com/project/Benio101/color-comment/branch/2017) on `ci.appveyor.com`.

I don't know why you are experiencing this issue since I've fixed all three `Color.*` extensions published to marketplace. There are only two options that comes to my mind right now:
- You've compiled the `master` instead of `2017` and installed on Visual Studio 2017.
- You didn't updated previous version of `Color.Comment`, which could yield such issue, or the partial update failed due to dependency issue, but didn't raise the error flag and rollback was not finished, leaving you with at least one package that depends VS 2019 package (v. `16.*`) from a VS 2017 (v. `15.*`) one.

In the later case, I suggest uninstalling current version of extension and installing version [`0.0.2+2017`](https://github.com/Benio101/Color.Comment/releases/tag/0.0.2%2B2017) (potentially again). If that won't help, tell me and I'll install VS 2017 again to test it.

Best regards.

**Comment by rani-pinchuk** [comment]
Hi Paweł,

The way I tried to install the extension is by clicking on the Download
green button in
https://marketplace.visualstudio.com/items?itemName=Benio.ColorComment. The
first time I tried to install it was the day I reported the issue - so
there is no previous version. In any case, I tried to uninstall and install
- but this did not help...

I suspect, though, that clicking on the Download button gives me version
0.01 and not 0.0.2 - at least this is the version mentioned in the
manifest.json file. Can it be that this is the issue?

Thanks and regards,

Rani

**Comment by Benio101** [comment]
> Can it be that this is the issue?

Yes. Thanks. It looks like marketplace still had `0.0.1` version, for some reason. My fault. I though it's updated. After installing Visual Studio 2017 again and testing, I've updated extension to version [`0.1.0.1`](https://github.com/Benio101/Color.Comment/releases/tag/0.1.0.1%2B2017) and renamed it to `Color.Comment (2017)`. There is also separate version for 2019: [Color.Comment 2019](https://marketplace.visualstudio.com/items?itemName=Benio.ColorComment2019).

Update installed extension from either github, marketplace or Visual Studio. Should be finally working now as expected as long as you have recent version of Visual Studio (updated to 15.9).

Thanks again.
