### ISSUE TITLE
Support for multiline comments and extra doxygen tags

### ISSUE THREAD

**Issue by rani-pinchuk** [Benio101/Color.Comment#3]
Hi Paweł,

# Feature request
## Basic informations

My colleagues are excited by your extension, as we use doxygen extensively. However, the documentation files we have are organized as one multiline comment:

```
namespace A::B {
/*!

\page A_B A page about B

\tableofcontents

@image html classA_11B__inherit__graph.svg

\subsection A_B_Intro Introduction

...

*/
}
```

and in addition we use many tags that are not colored by Color.Comment.

### Short Description
So the features requested:
1. Support for multiline comments - this can be done by including an option that enable / disable support for multiline comments.
2. Support for the more tags - we use a lot of tags, but mainly the following:

\b \e \c \details \n \image \mainpage \note \page \ref \return \retval \sa \section \see \snippet \subpage \subsection \subsubsection \tableofcontents \todo \verbatim \warning.
I am not sure how difficult it is to allow for options that define "new tags" in new colors (doxygen has plenty of tags, I guess you don't want to support all of them, but on the other hand, other users may prefer to see other tags with colors). 

Thanks and kind regards,

Rani

**Comment by Benio101** [comment]
I've been planning to add both those features definitelly in future.
I won't cheat you: I hate old and not object oriented microsoft _api_ used in visual studio extensions.

Adding multiline support, as well as custom tags to define are possible, but requires some cheaty workarounds. It's not fun to do, so I won't proritize it over other, mainly not open source projects. But since you've asked for it, I'll begin to work on it soon. Propably in next week as I have a lot of work in real life right now, too.

Thanks for your patience.
Best.

**Comment by TheJasperV** [comment]
Hi, is there any update on the timeline for this feature?

Jasper

**Comment by rani-pinchuk** [comment]
no update...

**Comment by Benio101** [comment]
Changing status to `Won't fix`, because abandoning the project. Sorry.
