### ISSUE TITLE
Define color rules with regex

### ISSUE THREAD

**Issue by WowItsDoge** [Benio101/Color.Comment#5]
# Feature request
### Short Description
It would be nice if rules could be defined like:
regex => color
So that the user can create a list with regex and color pairs to format the comments.

#### Pros
- more flexible than the current solution

#### Cons
- a little bit more complicated to use

### Relevance
There are no other Plugins in the Visual Studio Marktplace which support this feature.

**Comment by Benio101** [comment]
I've wanted to achieve this since beginning to be honest. Unfortunatelly, I did not found an easy way to provide such a feature in an extension. And now, I have abandoned the project so I'm changing status to `Won't fix`.
However, you mind find the [Color.Misc](https://github.com/Benio101/Color.Misc) template extension exactly what you're searching for to use. I've added a description for you. If you try, just look at those regex rules and customize them for you (then delete them all and write your own ones). Project requires simple building as a vsix extension, which is trivial and built in to a Visual Studio. Once built, install extension by running the generated `.vsix` file.
